require File.expand_path('../support/helpers', __FILE__)

describe_recipe "admin-user::default" do
  include Helpers::AdminUser

  it "creates /home/admin/.ssh/authorized_keys" do
    file("/home/admin/.ssh/authorized_keys").must_exist
    file("/home/admin/.ssh/authorized_keys").must_include '# Generated by Chef'
    file("/home/admin/.ssh/authorized_keys").must_include 'ssh-rsa DDDDB3NzaC1yc4EDDDDBIwDDDQED2MXYaKVT5w66G2wzKRiJ6h4MjtbWkkhiYpjxTX6Jk6DdNU5NBNOI9zo5F04YdoCKtoRDdLM+VV/cDkbi4lqAbg7uCN/XBmdNNRcNCZUeoVj0LYzoHZp7+WGa/9bCOXBaQp0FFW23Kp3QYrQ+GeIaN9gn1D/q/FRxp9h+U2w9se7WZcqJCqijBVfiyjCEOPMbcd+Flgg2E4s8Afa5Q6tk3JcXSPIbl2eToOZz0KjtchqYj+mD1VRZDF2DPY73sUqsVIIx9ngNNryfrFqtdHZEeOQVW7Z6B1aYDmTYOfrSW1NtuJ2ZKhsgdVsbi9VO76U3kLmyE+XnXeDtUXip/chRUw== admin@mymachine.local'
  end
end